
apiVersion: v1
kind: Service
metadata:
  name: golang-hello
  namespace: golang-hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: golang-hello
  type: LoadBalancer
