
apiVersion: v1
kind: Service
metadata:
  name: golang-hello
  namespace: golang-hello
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: golang-hello

