name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/golang-hello:latest

  deploy:
    runs-on: self-hosted    
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy Golang app
        run: |-
          kubectl get deployments,pods -n golang-hello
          ./kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment golang-hello -n golang-hello
          kubectl rollout -n golang-hello status deployment/golang-hello
          kubectl get deployments,pods -n golang-hello

