name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/golang-hello:latest

  deploy:
    runs-on: self-hosted    
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Display current state
        run: |
          kubectl get deployments,pods -n golang-hello
      - name: Apply changes and restart deployment
        run: |
          if ./kustomize build . | kubectl apply -f -; then
            echo "Changes applied successfully."
            if kubectl rollout restart deployment golang-hello -n golang-hello; then
              echo "Deployment restarted successfully."
              kubectl rollout status deployment/golang-hello -n golang-hello
              kubectl get deployments,pods -n golang-hello
            else
              echo "Failed to restart deployment."
              #kubectl rollout undo deployment/golang-hello -n golang-hello
              exit 1
            fi
          else
            echo "Failed to apply changes using Kustomize."
            #kubectl rollout undo deployment/golang-hello -n golang-hello
            exit 1
          fi
